[package]
name = "neural_tictactoe_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.14"
rand = "0.8.5"
rand_distr = "0.4.3"
nalgebra = "0.31.2"

